name: gh-pages

on:
 push: 
   branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: run build 
      run: |
        npm install
        npm run build
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        BRANCH: gh-pages # The branch the action should deploy to. 
        FOLDER: dist
